language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    secure: EaC12XhFg8EROI3io3W7WUPJbd/yivFZLq4eJFoHJ4n1s4vWNhcy8Yg1FxCQB7yS+yaTwYTFQ2B/Fl+T37bUfe6Ve0gr/f7MN+p4bJlF2o+LOA7Sfng35hD3lm1CstQ9MPDAdnRK4e/B4U6D34qgDCJR0DI3387jqXYgH4GG78c=
    - DB=mysql TYPO3_BRANCH=TYPO3_6-2 COVERAGE=0
    - DB=mysql TYPO3_BRANCH=master COVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=mysql TYPO3_BRANCH=master COVERAGE=1
  exclude:
    - php: 5.4
      env: DB=mysql TYPO3_BRANCH=master COVERAGE=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - derhansen@gmail.com

before_script:
  - cd ..
  - mkdir parallel && cd parallel && wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 && tar xvf parallel-latest.tar.bz2 -C . --strip-components=1 && ./configure && make && cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv sf_event_mgt typo3conf/ext/

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --colors -c typo3conf/ext/sf_event_mgt/Tests/Build/UnitTests.xml
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c typo3conf/ext/sf_event_mgt/Tests/Build/UnitTests.xml
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find . -wholename '*/typo3conf/ext/sf_event_mgt/Tests/Functional/*Test.php' | ./parallel/src/parallel --gnu --will-cite 'echo; echo "Running functional test suite {}"; ./bin/phpunit --coverage-clover={}functionaltest-coverage.clover --colors -c typo3conf/ext/sf_event_mgt/Tests/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      cp -R typo3conf/ext/sf_event_mgt/.git .
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      find . -wholename '*/typo3conf/ext/sf_event_mgt/Tests/Functional/*Test.php' -exec php ocular.phar code-coverage:upload --format=php-clover {}functionaltest-coverage.clover \;
    fi
