language: php

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - derhansen@gmail.com

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require nimut/typo3-complete="$TYPO3_VERSION"
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit -c Tests/Build/UnitTests.xml
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover -c Tests/Build/UnitTests.xml
    fi
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c Tests/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-clover={}functionaltest-coverage.clover -c Tests/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      cp -R typo3conf/ext/sf_event_mgt/.git .
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      find 'Tests/Functional' -wholename '*Test.php' -exec php ocular.phar code-coverage:upload --format=php-clover {}functionaltest-coverage.clover \;
    fi

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5 COVERAGE=1 FUNCTIONAL=0
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5 COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=1
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7 COVERAGE=0 FUNCTIONAL=0
